### ISSUE TITLE
Bailingquic.framework/Bailingquic, missing required architecture i386

### ISSUE THREAD

**Issue by tbfyniiswcy** [sealtalk/sealtalk-ios#25]
ld: warning: directory not found for option '-F/Users/william/universal/GitHub/sealtalk-ios/ios-rongimdemo/framework/PTT'
ld: warning: ignoring file /Users/william/universal/GitHub/sealtalk-ios/ios-rongimdemo/framework/Bailingquic.framework/Bailingquic, missing required architecture i386 in file /Users/william/universal/GitHub/sealtalk-ios/ios-rongimdemo/framework/Bailingquic.framework/Bailingquic (3 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_BailingquicQuicConn", referenced from:
      objc-class-ref in Blink(BinSocket.o)
  "_OBJC_CLASS_$_BailingquicHttpClient", referenced from:
      objc-class-ref in Blink(BlinkQuicHttp.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by JosephJue** [comment]
这个报错是缺少某些库。
下载了最新的demo源码，可以编译通过。
下载最新版本的试一下。
