### ISSUE TITLE
不能发布到app store

### ISSUE THREAD

**Issue by hold-my-hand** [sealtalk/sealtalk-ios#27]
During review, your app installed or launched executable code, which is not permitted on the App Store. Specifically, your app uses the itms-services URL scheme to install an app.

Please note that while educational apps designed to teach, develop, or allow students to test executable code may, in limited circumstances, download code, such code may not be used for other purposes and such apps must make the source code completely viewable and editable by the user.

The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.

这是苹果给出的审核被拒原因，因为这个原因还会导致审核时间延迟
看了下使用了很多第三方的库，而且URL Types中我全部删除了，还是因为这个选项被拒，还请告知到底是哪里出了问题
我targets只有Sealtalk这一项，那些extension，iwatch的项目都删除了

**Comment by JosephJue** [comment]
您尝试将“我 - 关于 SealTalk - SealTalk 版本”这个功能移除，这里使用了打开 URL 去更新的功能，更新的过程也就是覆盖安装 SealTalk。

**Comment by hold-my-hand** [comment]
- (void)checkVersion {
    [RCDHTTPTOOL getVersioncomplete:^(NSDictionary *versionInfo) {
        if (versionInfo) {
            NSString *isNeedUpdate = [versionInfo objectForKey:@"isNeedUpdate"];
            NSString *finalURL;
            if ([isNeedUpdate isEqualToString:@"YES"]) {
                __weak typeof(self) __weakSelf = self;
                [__weakSelf.tabBarController.tabBar showBadgeOnItemIndex:3];
                //获取系统当前的时间戳
                NSDate *dat = [NSDate dateWithTimeIntervalSinceNow:0];
                NSTimeInterval now = [dat timeIntervalSince1970] * 1000;
                NSString *timeString = [NSString stringWithFormat:@"%f", now];
                //为html增加随机数，避免缓存。
                NSString *applist = [versionInfo objectForKey:@"applist"];
                applist = [NSString stringWithFormat:@"%@?%@", applist, timeString];
                finalURL = [NSString stringWithFormat:@"itms-services://?action=download-manifest&url=%@", applist];
            }
            [[NSUserDefaults standardUserDefaults] setObject:finalURL forKey:@"applistURL"];
            [[NSUserDefaults standardUserDefaults] setObject:isNeedUpdate forKey:@"isNeedUpdate"];
            [[NSUserDefaults standardUserDefaults] synchronize];
        }
    }];
}
好的谢谢
