### ISSUE TITLE
刷新自定义cell

### ISSUE THREAD

**Issue by 15393713650** [sealtalk/sealtalk-ios#28]
自定义消息cell 计算了cell的高度是没问题的,可当我需要刷新cell重新设置高度时就出问题了,我调用[self.conversationMessageCollectionView reloadData];之后sizeForMessageModel:(RCMessageModel *)model
      withCollectionViewWidth:(CGFloat)collectionViewWidth
         referenceExtraHeight:(CGFloat)extraHeight的方法不会重新执行

**Comment by JosephJue** [comment]
您使用 indexPath 直接刷新具体的 cell 试一下。

**Comment by 15393713650** [comment]
[self.conversationMessageCollectionView reloadItemsAtIndexPaths:@[indexPath]];
这样也不会执行

**Comment by JosephJue** [comment]
需要将该 cell 对应的数据源中 model.cellSize = CGSizeZero;,再调用刷新方法。

/*!
 消息展示时的Cell高度

 @discussion 用于大量消息的显示优化
 */
@property(nonatomic) CGSize cellSize;
/*!

**Comment by 15393713650** [comment]
好的   已解决  谢谢
