### ISSUE TITLE
缺少文件RCDDiscussGroupSettingViewController.h

### ISSUE THREAD

**Issue by doubleGang** [sealtalk/sealtalk-ios#31]

**Comment by JosephJue** [comment]
RCDDiscussGroupSettingViewController 类已经被移除了。
如果您那边编译报错，清除本地缓存后再编译试一下。

**Comment by doubleGang** [comment]
不好使，你们自己有从github下载下来，测试吗？ 根本都跑不了



------------------ 原始邮件 ------------------
发件人: "JosephJue"<notifications@github.com>;
发送时间: 2019年8月1日(星期四) 下午2:05
收件人: "sealtalk/sealtalk-ios"<sealtalk-ios@noreply.github.com>;
抄送: "苦辣酸甜"<437974912@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sealtalk/sealtalk-ios] 缺少文件RCDDiscussGroupSettingViewController.h (#31)




RCDDiscussGroupSettingViewController 类已经被移除了。
 如果您那边编译报错，清除本地缓存后再编译试一下。

**Comment by JosephJue** [comment]
1. 升级 pod 到 1.7 版本
2. 升级后执行 pod repo update
3. 再 pod install 试一下

**Comment by doubleGang** [comment]
执行之后，还是原来的错误







------------------ 原始邮件 ------------------
发件人: "JosephJue"<notifications@github.com>;
发送时间: 2019年8月5日(星期一) 中午11:56
收件人: "sealtalk/sealtalk-ios"<sealtalk-ios@noreply.github.com>;
抄送: "苦辣酸甜"<437974912@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sealtalk/sealtalk-ios] 缺少文件RCDDiscussGroupSettingViewController.h (#31)



 
升级 pod 到 1.7 版本
 
升级后执行 pod repo update
 
再 pod install 试一下

**Comment by JosephJue** [comment]
贴一下错误的截图。

**Comment by doubleGang** [comment]
------------------ 原始邮件 ------------------
发件人: "JosephJue"<notifications@github.com>;
发送时间: 2019年8月5日(星期一) 下午2:11
收件人: "sealtalk/sealtalk-ios"<sealtalk-ios@noreply.github.com>;
抄送: "苦辣酸甜"<437974912@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sealtalk/sealtalk-ios] 缺少文件RCDDiscussGroupSettingViewController.h (#31)




贴一下错误的截图。
