### ISSUE TITLE
demo无法编译

### ISSUE THREAD

**Issue by lizheftd** [sealtalk/sealtalk-ios#32]
pod install时候报这个警告
The `SealTalk [Debug]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods-SealTalk/Pods-SealTalk.debug.xcconfig'. This can lead to problems with the CocoaPods installation
编译就报错

Showing Recent Messages
/Users/lizhe/Downloads/sealtalk-ios-master/ios-rongimdemo/Pods/Pods/Target Support Files/Pods-SealTalk/Pods-SealTalk.debug.xcconfig: unable to open file (in target "SealTalk" in project "RCloudMessage") (in target 'SealTalk')

**Comment by JosephJue** [comment]
升级 pod 到 1.7 版本后再 pod install 试一下。
