### ISSUE TITLE
发送宝贝的链接的功能？

### ISSUE THREAD

**Issue by zhufeng19940210** [sealtalk/sealtalk-ios#35]
请问集成融云SDK怎样做那个发送宝贝链接的功能？

**Comment by Zaria0619** [comment]
> 请问集成融云SDK怎样做那个发送宝贝链接的功能？

可以通过自定义消息的方式来做，自定义消息参考：https://support.rongcloud.cn/ks/NTMw

**Comment by zhufeng19940210** [comment]
好的，谢谢收到了
