### ISSUE TITLE
最新版运行不了

### ISSUE THREAD

**Issue by LixinQian** [sealtalk/sealtalk-ios#36]
报错日志如下： <img width="890" alt="屏幕快照 " src="https://user-images.githubusercontent.com/14228362/67307396-0a7eed00-f52b-11e9-94e0-61fd933ab19b.png">

**Comment by Zaria0619** [comment]
> 报错日志如下： <img alt="屏幕快照 " width="890" src="https://user-images.githubusercontent.com/14228362/67307396-0a7eed00-f52b-11e9-94e0-61fd933ab19b.png">

升级到 Xcode11 或者 SDK 降级到 2.9.24 以下版本
详细参见 https://stackoverflow.com/questions/57917069/apple-mach-o-linker-error-undefined-symbols-for-architecture-x86-64-uiscene

**Comment by JosephJue** [comment]
融云 SDK 2.9.25 版本兼容了 iOS 13 ，如果您需要兼容 iOS 13，那么请升级到 Xcode 11，来使用新版本的 Xcode；如果您不需要兼容 iOS 13 或者不想升级到 Xcode 11，那么请使用 2.9.24 版本的 SDK。
所以，如果 demo 使用了 2.9.25 版本的 SDK，就需要 Xcode 11 来编译。

**Comment by isdotjim** [comment]
搭个车...
想邀请你们来w3c.group创建项目对应的小组。w3c.group是类似知识星球的社群工具，但却不是知识付费性质的创作者社区，这里有相关的文章：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by SlinceDog** [comment]
Xcode 11 运行报错，这是什么原因？

Showing Recent Issues
/Users/daidonghan/Desktop/sealtalk-ios-2.9.25/ios-rongimdemo/Pods/Pods/Target Support Files/Pods-SealTalk/Pods-SealTalk.debug.xcconfig: unable to open file (in target "SealTalk" in project "RCloudMessage")

**Comment by JosephJue** [comment]
升级 pod 版本后，再执行 pod install，建议使用干净的 demo。

**Comment by adventureSCL** [comment]
![屏幕快照 2019-12-18 上午11 10 14](https://user-images.githubusercontent.com/24288194/71052670-15e74100-2187-11ea-9b97-2cc353604895.png)
我用2.9.24 也报这个错误是怎么回事呢？
