### ISSUE TITLE
xcode 11 报错编译不通过

### ISSUE THREAD

**Issue by SlinceDog** [sealtalk/sealtalk-ios#37]
Showing Recent Issues
/Users/daidonghan/Desktop/sealtalk-ios-2.9.25/ios-rongimdemo/Pods/Pods/Target Support Files/Pods-SealTalk/Pods-SealTalk.debug.xcconfig: unable to open file (in target "SealTalk" in project "RCloudMessage")

这是Demo具体报错

**Comment by JosephJue** [comment]
升级 pod 版本，再重新 pod install 后试一下。

**Comment by SlinceDog** [comment]
pod版本升级到1.8.4，代码都拉不下来，卡在Analyzing dependencies
不动。干净的demo，master也下载了，2.9.25也下载了，都不行

**Comment by JosephJue** [comment]
我这边 pod 的版本是  1.7.2，是正常可以 pod install 的。方便的话，可以使用这个版本试一下。
