### ISSUE TITLE
2.9.24 运行不了

### ISSUE THREAD

**Issue by kiwiSCL** [sealtalk/sealtalk-ios#39]
Xcode 版本为10.2.1 运行 2.9.24 报如下错误
![屏幕快照 2019-12-18 上午11 10 14](https://user-images.githubusercontent.com/24288194/71052774-62cb1780-2187-11ea-996b-f3586ca5de0f.png)

**Comment by adventureSCL** [comment]
ld: warning: directory not found for option '-F/Users/xixikeji/Downloads/sealtalk-ios-2.9.24/ios-rongimdemo/framework/JrmfIMLib'
ld: warning: directory not found for option '-F/Users/xixikeji/Downloads/sealtalk-ios-2.9.24/ios-rongimdemo/framework/AlipaySDK'
ld: warning: directory not found for option '-F/Users/xixikeji/Downloads/sealtalk-ios-2.9.24/ios-rongimdemo/framework/ifly'
ld: warning: directory not found for option '-F/Users/xixikeji/Downloads/sealtalk-ios-2.9.24/ios-rongimdemo/framework/RCSticker'
Undefined symbols for architecture x86_64:
  "___isPlatformVersionAtLeast", referenced from:
      -[JrmfTransferStatusViewController viewDidLoad] in JrmfPacketKit(JrmfTransferStatusViewController.o)
      -[PacketCardListViewController cardList] in JrmfPacketKit(PacketCardListViewController.o)
      -[JYPacketViewController viewDidLoad] in JrmfPacketKit(JYPacketViewController.o)
      -[JrmfMyPacketViewController tableViewWithTage:] in JrmfPacketKit(JrmfMyPacketViewController.o)
      -[JrmfOPacketDetailViewController packetList] in JrmfPacketKit(JrmfOPacketDetailViewController.o)
      -[JrmfPckTransRecordViewController transList] in JrmfPacketKit(JrmfPckTransRecordViewController.o)
      -[WalletbankCardSetViewController cardList] in JrmfWalletKit(WalletbankCardSetViewController.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by JosephJue** [comment]
是 iOS 13 的适配问题，建议：
1. 升级 Xcode11。
2. 升级 SDK 到 2.10.1 版本。

**Comment by kiwiSCL** [comment]
升级 Xcode11。
升级 SDK 到 2.10.1 版本。解决
