### ISSUE TITLE
请问如果要自定义图片消息应该怎么做？按自定义文字消息来做不了

### ISSUE THREAD

**Issue by kiwiSCL** [sealtalk/sealtalk-ios#41]

**Comment by JosephJue** [comment]
思路是一样的，只是比文本消息多一些处理：
1. 图片消息需要自己将原图上传后的地址设置到消息中。
2. 缩略图可以用 base64 编码形式设置到消息中。
3. 发送方：可以设置 localPath，展示时候使用 localPath 的图片来展示。
4. 接收方：需要根据消息中的图片远程地址下载图片，下载完成来展示，下载过程中可以展示缩略图且加入下载的动画。

**Comment by kiwiSCL** [comment]
+ (RCMessagePersistent)persistentFlag {
    return (MessagePersistent_ISPERSISTED | MessagePersistent_ISCOUNTED);
}

/// NSCoding
- (instancetype)initWithCoder:(NSCoder *)aDecoder {
    self = [super init];
    if (self) {
        self.extra = [aDecoder decodeObjectForKey:@"extra"];
//        self.timeIntvar = [aDecoder decodeObjectForKey:@"timeIntvar"];
        self.times = [aDecoder decodeObjectForKey:@"times"];
        self.imageUrl = [aDecoder decodeObjectForKey:@"imageUrl"];
        self.localPath = [aDecoder decodeObjectForKey:@"localPath"];
//        self.thumbnailImage = [aDecoder decodeObjectForKey:@"thumbnailImage"];
//        self.originalImage = [aDecoder decodeObjectForKey:@"originalImage"];
        
        self.thumbnailImage =[UIImage imageWithData:[NSData dataWithContentsOfFile:[aDecoder decodeObjectForKey:@"thumbnailImage"]]];
        self.originalImage =[UIImage imageWithData:[NSData dataWithContentsOfFile:[aDecoder decodeObjectForKey:@"originalImage"]]] ;

        
    }
    return self;
}

/// NSCoding
- (void)encodeWithCoder:(NSCoder *)aCoder {
    [aCoder encodeObject:self.extra forKey:@"extra"];
//    [aCoder encodeObject:self.timeIntvar forKey:@"timeIntvar"];
    [aCoder encodeObject:self.times forKey:@"times"];
    [aCoder encodeObject:self.imageUrl forKey:@"imageUrl"];
    [aCoder encodeObject:self.localPath forKey:@"localPath"];
    
//    [aCoder encodeObject:self.thumbnailImage forKey:@"thumbnailImage"];
//    [aCoder encodeObject:self.originalImage forKey:@"originalImage"];
    
    [aCoder encodeObject:UIImageJPEGRepresentation(self.thumbnailImage,1.0f) forKey:@"thumbnailImage"];
    [aCoder encodeObject:UIImageJPEGRepresentation(self.originalImage,1.0f) forKey:@"originalImage"];
}

///将消息内容编码成json
- (NSData *)encode {
    NSMutableDictionary *dataDict = [NSMutableDictionary dictionary];
//    [dataDict setObject:self.timeIntvar forKey:@"timeIntvar"];
    [dataDict setObject:self.times forKey:@"times"];

    if (self.imageUrl) {
        [dataDict setObject:self.imageUrl forKey:@"imageUrl"];
    }
    if (self.localPath) {
        [dataDict setObject:self.localPath forKey:@"localPath"];
    }
    if (self.extra) {
        [dataDict setObject:self.extra forKey:@"extra"];
    }
//    if (self.thumbnailImage) {
//        [dataDict setObject:[[NSData alloc] initWithBase64EncodedData:UIImageJPEGRepresentation(self.thumbnailImage,1.0f) options:0] forKey:@"thumbnailImage"];
//    }
//    if (self.originalImage) {
//        [dataDict setObject:[[NSData alloc] initWithBase64EncodedData:UIImageJPEGRepresentation(self.originalImage,1.0f) options:0] forKey:@"originalImage"];
//    }
        
    if (self.senderUserInfo) {
        NSMutableDictionary *userInfoDic = [[NSMutableDictionary alloc] init];
        if (self.senderUserInfo.name) {
            [userInfoDic setObject:self.senderUserInfo.name forKeyedSubscript:@"name"];
        }
        if (self.senderUserInfo.portraitUri) {
            [userInfoDic setObject:self.senderUserInfo.portraitUri forKeyedSubscript:@"portrait"];
        }
        if (self.senderUserInfo.userId) {
            [userInfoDic setObject:self.senderUserInfo.userId forKeyedSubscript:@"id"];
        }
        [dataDict setObject:userInfoDic forKey:@"user"];
    }
    NSData *data = [NSJSONSerialization dataWithJSONObject:dataDict options:kNilOptions error:nil];
    return data;
}

///将json解码生成消息内容
- (void)decodeWithData:(NSData *)data {
    if (data) {
        __autoreleasing NSError *error = nil;

        NSDictionary *dictionary = [NSJSONSerialization JSONObjectWithData:data options:kNilOptions error:&error];

        if (dictionary) {
            self.extra = dictionary[@"extra"];
//            self.timeIntvar = dictionary[@"timeIntvar"];
            self.times = dictionary[@"times"];
            self.imageUrl = dictionary[@"imageUrl"];
            self.localPath = dictionary[@"localPath"];
            
            self.thumbnailImage =[UIImage imageWithData:[NSData dataWithContentsOfFile:dictionary[@"thumbnailImage"]]];
            self.originalImage =[UIImage imageWithData:[NSData dataWithContentsOfFile:dictionary[@"originalImage"]]] ;

//            self.originalImage = dictionary[@"originalImage"];
            NSDictionary *userinfoDic = dictionary[@"user"];
            [self decodeUserInfo:userinfoDic];
        }
    }
}


一直卡在这里，好像怎么处理图片都不对。请问应该怎么写才合理？？？

**Comment by kiwiSCL** [comment]
继承自RCMediaMessageContent 后我应该怎么初始化/*!
UIImage *thumbnailImage;
 UIImage *originalImage;
这两个属性，请教一下大神

**Comment by JosephJue** [comment]
thumbnailImage 是缩略图，使用原图按一定比例压缩，分辨率不需要很高，可以在消息中携带，以 base64 编码的形式。

originalImage 是原始图，上传图片时候使用，上传后将地址在消息中携带，接收方使用地址下载原图。
