### ISSUE TITLE
RCDTestMessageCell 注册失败？？？

### ISSUE THREAD

**Issue by xiaoxiaoyuxie** [sealtalk/sealtalk-ios#48]
///注册自定义测试消息Cell
    [self registerClass:RCDTestMessageCell.class forMessageClass:RCDTestMessage.class];

这句什么情况下会执行RCDTestMessageCell的初始化方法呢？ 把所有消息类型都试过了

**Comment by Zaria0619** [comment]
你需要发送一个RCDTestMessage类型的消息，这样会话数据有这个数据，才会展示相关UI
