### ISSUE TITLE
最新版报错

### ISSUE THREAD

**Issue by Manjusaka-iOS** [sealtalk/sealtalk-ios#6]
![2a57f263-0c6c-480b-8dc1-f9be471f85b6](https://cloud.githubusercontent.com/assets/24203564/23645342/9c3ceda2-0346-11e7-8b11-691da4f77714.png)

**Comment by shumintao** [comment]
built Stting  -- auto manager  --取消 就行了 （别自动识别证书 ）

**Comment by Master-YANGYONGQIANG** [comment]
模拟器运行可以 真机运行报上图同样的错误 怎么解决
