### ISSUE TITLE
你好 集成你们的代码 编译报错 如何解决呢？

### ISSUE THREAD

**Issue by jj89757hhb** [sealtalk/sealtalk-ios#8]
duplicate symbol _hud in:
    /Users/xuetianhhb/Library/Developer/Xcode/DerivedData/ShuiYouHui-eygpaasafqmjzaaomxdkaruzrrip/Build/Intermediates/ShuiYouHui.build/Debug-iphonesimulator/ShuiYouHui.build/Objects-normal/x86_64/RealTimeLocationViewController.o
    /Users/xuetianhhb/Library/Developer/Xcode/DerivedData/ShuiYouHui-eygpaasafqmjzaaomxdkaruzrrip/Build/Intermediates/ShuiYouHui.build/Debug-iphonesimulator/ShuiYouHui.build/Objects-normal/x86_64/RCDAddressBookViewController.o
duplicate symbol _hud in:
    /Users/xuetianhhb/Library/Developer/Xcode/DerivedData/ShuiYouHui-eygpaasafqmjzaaomxdkaruzrrip/Build/Intermediates/ShuiYouHui.build/Debug-iphonesimulator/ShuiYouHui.build/Objects-normal/x86_64/RealTimeLocationViewController.o
    /Users/xuetianhhb/Library/Developer/Xcode/DerivedData/ShuiYouHui-eygpaasafqmjzaaomxdkaruzrrip/Build/Intermediates/ShuiYouHui.build/Debug-iphonesimulator/ShuiYouHui.build/Objects-normal/x86_64/RCDLoginViewController2.o
duplicate symbol _hud in:
    /Users/xuetianhhb/Library/Developer/Xcode/DerivedData/ShuiYouHui-eygpaasafqmjzaaomxdkaruzrrip/Build/Intermediates/ShuiYouHui.build/Debug-iphonesimulator/ShuiYouHui.build/Objects-normal/x86_64/RealTimeLocationViewController.o
    /Users/xuetianhhb/Library/Developer/Xcode/DerivedData/ShuiYouHui-eygpaasafqmjzaaomxdkaruzrrip/Build/Intermediates/ShuiYouHui.build/Debug-iphonesimulator/ShuiYouHui.build/Objects-normal/x86_64/ContactSelectedTableViewController.o
ld: 3 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by waitforsomeone** [comment]
SortForTime 全局搜下这个文件可能重复添加了

**Comment by JosephJue** [comment]
工程中导入了重复的类。
